using RetroDev.UISharp.Core.Windowing.Events;
using static SDL2.SDL;

namespace RetroDev.UISharp.Core.Windowing.SDL;

/// <summary>
/// Maps the SDL keyboard keys defined in <see cref="SDL_Keycode"/> to <see cref="KeyButton"/>.
/// </summary>
public static class SDLKeyButtonMapping
{
    private static readonly Dictionary<SDL_Keycode, KeyButton> s_sdlToKeyButtonMap = new()
    {
        { SDL_Keycode.SDLK_UNKNOWN, KeyButton.Unknown },
        { SDL_Keycode.SDLK_RETURN, KeyButton.Return },
        { SDL_Keycode.SDLK_ESCAPE, KeyButton.Escape },
        { SDL_Keycode.SDLK_BACKSPACE, KeyButton.Backspace },
        { SDL_Keycode.SDLK_TAB, KeyButton.Tab },
        { SDL_Keycode.SDLK_SPACE, KeyButton.Space },
        { SDL_Keycode.SDLK_EXCLAIM, KeyButton.Exclaim },
        { SDL_Keycode.SDLK_QUOTEDBL, KeyButton.DoubleQuote },
        { SDL_Keycode.SDLK_HASH, KeyButton.Hash },
        { SDL_Keycode.SDLK_PERCENT, KeyButton.Percent },
        { SDL_Keycode.SDLK_DOLLAR, KeyButton.Dollar },
        { SDL_Keycode.SDLK_AMPERSAND, KeyButton.Ampersand },
        { SDL_Keycode.SDLK_QUOTE, KeyButton.Quote },
        { SDL_Keycode.SDLK_LEFTPAREN, KeyButton.LeftParenthesis },
        { SDL_Keycode.SDLK_RIGHTPAREN, KeyButton.RightParenthesis },
        { SDL_Keycode.SDLK_ASTERISK, KeyButton.Asterisk },
        { SDL_Keycode.SDLK_PLUS, KeyButton.Plus },
        { SDL_Keycode.SDLK_COMMA, KeyButton.Comma },
        { SDL_Keycode.SDLK_MINUS, KeyButton.Minus },
        { SDL_Keycode.SDLK_PERIOD, KeyButton.Period },
        { SDL_Keycode.SDLK_SLASH, KeyButton.Slash },
        { SDL_Keycode.SDLK_0, KeyButton.Number0 },
        { SDL_Keycode.SDLK_1, KeyButton.Number1 },
        { SDL_Keycode.SDLK_2, KeyButton.Number2 },
        { SDL_Keycode.SDLK_3, KeyButton.Number3 },
        { SDL_Keycode.SDLK_4, KeyButton.Number4 },
        { SDL_Keycode.SDLK_5, KeyButton.Number5 },
        { SDL_Keycode.SDLK_6, KeyButton.Number6 },
        { SDL_Keycode.SDLK_7, KeyButton.Number7 },
        { SDL_Keycode.SDLK_8, KeyButton.Number8 },
        { SDL_Keycode.SDLK_9, KeyButton.Number9 },
        { SDL_Keycode.SDLK_COLON, KeyButton.Colon },
        { SDL_Keycode.SDLK_SEMICOLON, KeyButton.Semicolon },
        { SDL_Keycode.SDLK_LESS, KeyButton.LessThan },
        { SDL_Keycode.SDLK_EQUALS, KeyButton.Equals },
        { SDL_Keycode.SDLK_GREATER, KeyButton.GreaterThan },
        { SDL_Keycode.SDLK_QUESTION, KeyButton.QuestionMark },
        { SDL_Keycode.SDLK_AT, KeyButton.At },
        { SDL_Keycode.SDLK_LEFTBRACKET, KeyButton.LeftSquareBracket },
        { SDL_Keycode.SDLK_BACKSLASH, KeyButton.Backslash },
        { SDL_Keycode.SDLK_RIGHTBRACKET, KeyButton.RightSquareBracket },
        { SDL_Keycode.SDLK_CARET, KeyButton.Caret },
        { SDL_Keycode.SDLK_UNDERSCORE, KeyButton.Underscore },
        { SDL_Keycode.SDLK_BACKQUOTE, KeyButton.Backtick },
        { SDL_Keycode.SDLK_a, KeyButton.A },
        { SDL_Keycode.SDLK_b, KeyButton.B },
        { SDL_Keycode.SDLK_c, KeyButton.C },
        { SDL_Keycode.SDLK_d, KeyButton.D },
        { SDL_Keycode.SDLK_e, KeyButton.E },
        { SDL_Keycode.SDLK_f, KeyButton.F },
        { SDL_Keycode.SDLK_g, KeyButton.G },
        { SDL_Keycode.SDLK_h, KeyButton.H },
        { SDL_Keycode.SDLK_i, KeyButton.I },
        { SDL_Keycode.SDLK_j, KeyButton.J },
        { SDL_Keycode.SDLK_k, KeyButton.K },
        { SDL_Keycode.SDLK_l, KeyButton.L },
        { SDL_Keycode.SDLK_m, KeyButton.M },
        { SDL_Keycode.SDLK_n, KeyButton.N },
        { SDL_Keycode.SDLK_o, KeyButton.O },
        { SDL_Keycode.SDLK_p, KeyButton.P },
        { SDL_Keycode.SDLK_q, KeyButton.Q },
        { SDL_Keycode.SDLK_r, KeyButton.R },
        { SDL_Keycode.SDLK_s, KeyButton.S },
        { SDL_Keycode.SDLK_t, KeyButton.T },
        { SDL_Keycode.SDLK_u, KeyButton.U },
        { SDL_Keycode.SDLK_v, KeyButton.V },
        { SDL_Keycode.SDLK_w, KeyButton.W },
        { SDL_Keycode.SDLK_x, KeyButton.X },
        { SDL_Keycode.SDLK_y, KeyButton.Y },
        { SDL_Keycode.SDLK_z, KeyButton.Z },
        { SDL_Keycode.SDLK_CAPSLOCK, KeyButton.CapsLock },
        { SDL_Keycode.SDLK_F1, KeyButton.F1 },
        { SDL_Keycode.SDLK_F2, KeyButton.F2 },
        { SDL_Keycode.SDLK_F3, KeyButton.F3 },
        { SDL_Keycode.SDLK_F4, KeyButton.F4 },
        { SDL_Keycode.SDLK_F5, KeyButton.F5 },
        { SDL_Keycode.SDLK_F6, KeyButton.F6 },
        { SDL_Keycode.SDLK_F7, KeyButton.F7 },
        { SDL_Keycode.SDLK_F8, KeyButton.F8 },
        { SDL_Keycode.SDLK_F9, KeyButton.F9 },
        { SDL_Keycode.SDLK_F10, KeyButton.F10 },
        { SDL_Keycode.SDLK_F11, KeyButton.F11 },
        { SDL_Keycode.SDLK_F12, KeyButton.F12 },
        { SDL_Keycode.SDLK_PRINTSCREEN, KeyButton.PrintScreen },
        { SDL_Keycode.SDLK_SCROLLLOCK, KeyButton.ScrollLock },
        { SDL_Keycode.SDLK_PAUSE, KeyButton.Pause },
        { SDL_Keycode.SDLK_INSERT, KeyButton.Insert },
        { SDL_Keycode.SDLK_HOME, KeyButton.Home },
        { SDL_Keycode.SDLK_PAGEUP, KeyButton.PageUp },
        { SDL_Keycode.SDLK_DELETE, KeyButton.Delete },
        { SDL_Keycode.SDLK_END, KeyButton.End },
        { SDL_Keycode.SDLK_PAGEDOWN, KeyButton.PageDown },
        { SDL_Keycode.SDLK_RIGHT, KeyButton.Right },
        { SDL_Keycode.SDLK_LEFT, KeyButton.Left },
        { SDL_Keycode.SDLK_DOWN, KeyButton.Down },
        { SDL_Keycode.SDLK_UP, KeyButton.Up },
        { SDL_Keycode.SDLK_NUMLOCKCLEAR, KeyButton.NumLockClear },
        { SDL_Keycode.SDLK_KP_DIVIDE, KeyButton.KeyPadDivide },
        { SDL_Keycode.SDLK_KP_MULTIPLY, KeyButton.KeyPadMultiply },
        { SDL_Keycode.SDLK_KP_MINUS, KeyButton.KeyPadMinus },
        { SDL_Keycode.SDLK_KP_PLUS, KeyButton.KeyPadPlus },
        { SDL_Keycode.SDLK_KP_ENTER, KeyButton.KeyPadEnter },
        { SDL_Keycode.SDLK_KP_1, KeyButton.KeyPad1 },
        { SDL_Keycode.SDLK_KP_2, KeyButton.KeyPad2 },
        { SDL_Keycode.SDLK_KP_3, KeyButton.KeyPad3 },
        { SDL_Keycode.SDLK_KP_4, KeyButton.KeyPad4 },
        { SDL_Keycode.SDLK_KP_5, KeyButton.KeyPad5 },
        { SDL_Keycode.SDLK_KP_6, KeyButton.KeyPad6 },
        { SDL_Keycode.SDLK_KP_7, KeyButton.KeyPad7 },
        { SDL_Keycode.SDLK_KP_8, KeyButton.KeyPad8 },
        { SDL_Keycode.SDLK_KP_9, KeyButton.KeyPad9 },
        { SDL_Keycode.SDLK_KP_0, KeyButton.KeyPad0 },
        { SDL_Keycode.SDLK_KP_PERIOD, KeyButton.KeyPadPeriod },
        { SDL_Keycode.SDLK_APPLICATION, KeyButton.Application },
        { SDL_Keycode.SDLK_POWER, KeyButton.Power },
        { SDL_Keycode.SDLK_KP_EQUALS, KeyButton.KeyPadEquals },
        { SDL_Keycode.SDLK_F13, KeyButton.F13 },
        { SDL_Keycode.SDLK_F14, KeyButton.F14 },
        { SDL_Keycode.SDLK_F15, KeyButton.F15 },
        { SDL_Keycode.SDLK_F16, KeyButton.F16 },
        { SDL_Keycode.SDLK_F17, KeyButton.F17 },
        { SDL_Keycode.SDLK_F18, KeyButton.F18 },
        { SDL_Keycode.SDLK_F19, KeyButton.F19 },
        { SDL_Keycode.SDLK_F20, KeyButton.F20 },
        { SDL_Keycode.SDLK_F21, KeyButton.F21 },
        { SDL_Keycode.SDLK_F22, KeyButton.F22 },
        { SDL_Keycode.SDLK_F23, KeyButton.F23 },
        { SDL_Keycode.SDLK_F24, KeyButton.F24 },
        { SDL_Keycode.SDLK_EXECUTE, KeyButton.Execute },
        { SDL_Keycode.SDLK_HELP, KeyButton.Help },
        { SDL_Keycode.SDLK_MENU, KeyButton.Menu },
        { SDL_Keycode.SDLK_SELECT, KeyButton.Select },
        { SDL_Keycode.SDLK_STOP, KeyButton.Stop },
        { SDL_Keycode.SDLK_AGAIN, KeyButton.Again },
        { SDL_Keycode.SDLK_UNDO, KeyButton.Undo },
        { SDL_Keycode.SDLK_CUT, KeyButton.Cut },
        { SDL_Keycode.SDLK_COPY, KeyButton.Copy },
        { SDL_Keycode.SDLK_PASTE, KeyButton.Paste },
        { SDL_Keycode.SDLK_FIND, KeyButton.Find },
        { SDL_Keycode.SDLK_MUTE, KeyButton.Mute },
        { SDL_Keycode.SDLK_VOLUMEUP, KeyButton.VolumeUp },
        { SDL_Keycode.SDLK_VOLUMEDOWN, KeyButton.VolumeDown },
        { SDL_Keycode.SDLK_KP_COMMA, KeyButton.KeyPadComma },
        { SDL_Keycode.SDLK_KP_EQUALSAS400, KeyButton.KeyPadEqualsAS400 },
        { SDL_Keycode.SDLK_ALTERASE, KeyButton.AltErase },
        { SDL_Keycode.SDLK_SYSREQ, KeyButton.SysReq },
        { SDL_Keycode.SDLK_CANCEL, KeyButton.Cancel },
        { SDL_Keycode.SDLK_CLEAR, KeyButton.Clear },
        { SDL_Keycode.SDLK_PRIOR, KeyButton.Prior },
        { SDL_Keycode.SDLK_RETURN2, KeyButton.Return2 },
        { SDL_Keycode.SDLK_SEPARATOR, KeyButton.Separator },
        { SDL_Keycode.SDLK_OUT, KeyButton.Out },
        { SDL_Keycode.SDLK_OPER, KeyButton.Oper },
        { SDL_Keycode.SDLK_CLEARAGAIN, KeyButton.ClearAgain },
        { SDL_Keycode.SDLK_CRSEL, KeyButton.CRSel },
        { SDL_Keycode.SDLK_EXSEL, KeyButton.ExSel },
        { SDL_Keycode.SDLK_KP_00, KeyButton.KeyPad00 },
        { SDL_Keycode.SDLK_KP_000, KeyButton.KeyPad000 },
        { SDL_Keycode.SDLK_THOUSANDSSEPARATOR, KeyButton.ThousandsSeparator },
        { SDL_Keycode.SDLK_DECIMALSEPARATOR, KeyButton.DecimalSeparator },
        { SDL_Keycode.SDLK_CURRENCYUNIT, KeyButton.CurrencyUnit },
        { SDL_Keycode.SDLK_CURRENCYSUBUNIT, KeyButton.CurrencySubunit },
        { SDL_Keycode.SDLK_KP_LEFTPAREN, KeyButton.KeyPadLeftParen },
        { SDL_Keycode.SDLK_KP_RIGHTPAREN, KeyButton.KeyPadRightParen },
        { SDL_Keycode.SDLK_KP_LEFTBRACE, KeyButton.KeyPadLeftBrace },
        { SDL_Keycode.SDLK_KP_RIGHTBRACE, KeyButton.KeyPadRightBrace },
        { SDL_Keycode.SDLK_KP_TAB, KeyButton.KeyPadTab },
        { SDL_Keycode.SDLK_KP_BACKSPACE, KeyButton.KeyPadBackspace },
        { SDL_Keycode.SDLK_KP_A, KeyButton.KeyPadA },
        { SDL_Keycode.SDLK_KP_B, KeyButton.KeyPadB },
        { SDL_Keycode.SDLK_KP_C, KeyButton.KeyPadC },
        { SDL_Keycode.SDLK_KP_D, KeyButton.KeyPadD },
        { SDL_Keycode.SDLK_KP_E, KeyButton.KeyPadE },
        { SDL_Keycode.SDLK_KP_F, KeyButton.KeyPadF },
        { SDL_Keycode.SDLK_KP_XOR, KeyButton.KeyPadXOR },
        { SDL_Keycode.SDLK_KP_POWER, KeyButton.KeyPadPower },
        { SDL_Keycode.SDLK_KP_PERCENT, KeyButton.KeyPadPercent },
        { SDL_Keycode.SDLK_KP_LESS, KeyButton.KeyPadLess },
        { SDL_Keycode.SDLK_KP_GREATER, KeyButton.KeyPadGreater },
        { SDL_Keycode.SDLK_KP_AMPERSAND, KeyButton.KeyPadAmpersand },
        { SDL_Keycode.SDLK_KP_DBLAMPERSAND, KeyButton.KeyPadDoubleAmpersand },
        { SDL_Keycode.SDLK_KP_VERTICALBAR, KeyButton.KeyPadVerticalBar },
        { SDL_Keycode.SDLK_KP_DBLVERTICALBAR, KeyButton.KeyPadDoubleVerticalBar },
        { SDL_Keycode.SDLK_KP_COLON, KeyButton.KeyPadColon },
        { SDL_Keycode.SDLK_KP_HASH, KeyButton.KeyPadHash },
        { SDL_Keycode.SDLK_KP_SPACE, KeyButton.KeyPadSpace },
        { SDL_Keycode.SDLK_KP_AT, KeyButton.KeyPadAt },
        { SDL_Keycode.SDLK_KP_EXCLAM, KeyButton.KeyPadExclam },
        { SDL_Keycode.SDLK_KP_MEMSTORE, KeyButton.KeyPadMemStore },
        { SDL_Keycode.SDLK_KP_MEMRECALL, KeyButton.KeyPadMemRecall },
        { SDL_Keycode.SDLK_KP_MEMCLEAR, KeyButton.KeyPadMemClear },
        { SDL_Keycode.SDLK_KP_MEMADD, KeyButton.KeyPadMemAdd },
        { SDL_Keycode.SDLK_KP_MEMSUBTRACT, KeyButton.KeyPadMemSubtract },
        { SDL_Keycode.SDLK_KP_MEMMULTIPLY, KeyButton.KeyPadMemMultiply },
        { SDL_Keycode.SDLK_KP_MEMDIVIDE, KeyButton.KeyPadMemDivide },
        { SDL_Keycode.SDLK_KP_PLUSMINUS, KeyButton.KeyPadPlusMinus },
        { SDL_Keycode.SDLK_KP_CLEAR, KeyButton.KeyPadClear },
        { SDL_Keycode.SDLK_KP_CLEARENTRY, KeyButton.KeyPadClearEntry },
        { SDL_Keycode.SDLK_KP_BINARY, KeyButton.KeyPadBinary },
        { SDL_Keycode.SDLK_KP_OCTAL, KeyButton.KeyPadOctal },
        { SDL_Keycode.SDLK_KP_DECIMAL, KeyButton.KeyPadDecimal },
        { SDL_Keycode.SDLK_KP_HEXADECIMAL, KeyButton.KeyPadHexadecimal },
        { SDL_Keycode.SDLK_LCTRL, KeyButton.LeftControl },
        { SDL_Keycode.SDLK_LSHIFT, KeyButton.LeftShift },
        { SDL_Keycode.SDLK_LALT, KeyButton.LeftAlt },
        { SDL_Keycode.SDLK_LGUI, KeyButton.LeftGUI },
        { SDL_Keycode.SDLK_RCTRL, KeyButton.RightControl },
        { SDL_Keycode.SDLK_RSHIFT, KeyButton.RightShift },
        { SDL_Keycode.SDLK_RALT, KeyButton.RightAlt },
        { SDL_Keycode.SDLK_RGUI, KeyButton.RightGUI },
        { SDL_Keycode.SDLK_MODE, KeyButton.Mode },
        { SDL_Keycode.SDLK_AUDIONEXT, KeyButton.AudioNext },
        { SDL_Keycode.SDLK_AUDIOPREV, KeyButton.AudioPrev },
        { SDL_Keycode.SDLK_AUDIOSTOP, KeyButton.AudioStop },
        { SDL_Keycode.SDLK_AUDIOPLAY, KeyButton.AudioPlay },
        { SDL_Keycode.SDLK_AUDIOMUTE, KeyButton.AudioMute },
        { SDL_Keycode.SDLK_MEDIASELECT, KeyButton.MediaSelect },
        { SDL_Keycode.SDLK_WWW, KeyButton.WWW },
        { SDL_Keycode.SDLK_MAIL, KeyButton.Mail },
        { SDL_Keycode.SDLK_CALCULATOR, KeyButton.Calculator },
        { SDL_Keycode.SDLK_COMPUTER, KeyButton.Computer },
        { SDL_Keycode.SDLK_AC_SEARCH, KeyButton.ACSearch },
        { SDL_Keycode.SDLK_AC_HOME, KeyButton.ACHome },
        { SDL_Keycode.SDLK_AC_BACK, KeyButton.ACBack },
        { SDL_Keycode.SDLK_AC_FORWARD, KeyButton.ACForward },
        { SDL_Keycode.SDLK_AC_STOP, KeyButton.ACStop },
        { SDL_Keycode.SDLK_AC_REFRESH, KeyButton.ACRefresh },
        { SDL_Keycode.SDLK_AC_BOOKMARKS, KeyButton.ACBookmarks },
        { SDL_Keycode.SDLK_BRIGHTNESSDOWN, KeyButton.BrightnessDown },
        { SDL_Keycode.SDLK_BRIGHTNESSUP, KeyButton.BrightnessUp },
        { SDL_Keycode.SDLK_DISPLAYSWITCH, KeyButton.DisplaySwitch },
        { SDL_Keycode.SDLK_KBDILLUMTOGGLE, KeyButton.KeyPadIllumToggle },
        { SDL_Keycode.SDLK_KBDILLUMDOWN, KeyButton.KeyPadIllumDown },
        { SDL_Keycode.SDLK_KBDILLUMUP, KeyButton.KeyPadIllumUp },
        { SDL_Keycode.SDLK_EJECT, KeyButton.Eject },
        { SDL_Keycode.SDLK_SLEEP, KeyButton.Sleep },
        { SDL_Keycode.SDLK_APP1, KeyButton.App1 },
        { SDL_Keycode.SDLK_APP2, KeyButton.App2 },
        { SDL_Keycode.SDLK_AUDIOREWIND, KeyButton.AudioRewind },
        { SDL_Keycode.SDLK_AUDIOFASTFORWARD, KeyButton.AudioFastForward }
    };

    /// <summary>
    /// Returns the <see cref="KeyButton"/> equivalent to the given <paramref name="sdlKeycode"/>.
    /// </summary>
    /// <param name="sdlKeycode">The SDL key code to convert.</param>
    /// <returns>The equivalent <see cref="KeyButton"/>.</returns>
    /// <remarks>
    /// Having a SDL enum and a framework equivlent enum is necessary since all SDL specific code is
    /// provided by interface implementation and SDL can be replaced by other technologies.
    /// </remarks>
    public static KeyButton ToKeyButton(SDL_Keycode sdlKeycode)
    {
        return s_sdlToKeyButtonMap.TryGetValue(sdlKeycode, out var keyButton) ? keyButton : KeyButton.Unknown;
    }
}
