using RetroDev.OpenUI.Exceptions;
using SDL2;

namespace RetroDev.OpenUI.Core.Internal;

// TODO: add more window options (size, location, style like without borders, etc.)
internal class SDLWindowManager : IWindowManager
{
    private readonly LifeCycle _lifeCycle;
    private readonly IntPtr _window;
    private bool _visible;

    public SDLWindowManager(LifeCycle lifeCycle)
    {
        _lifeCycle = lifeCycle;

        _window = SDL.SDL_CreateWindow("Test widnow",
                                       SDL.SDL_WINDOWPOS_CENTERED,
                                       SDL.SDL_WINDOWPOS_CENTERED,
                                       800, 600,
                                       SDL.SDL_WindowFlags.SDL_WINDOW_HIDDEN);

        if (_window == IntPtr.Zero) throw new UIInitializationException($"Error creating window: {SDL.SDL_GetError()}");
        RenderingEngine = new SDLRenderingEngine(_lifeCycle, _window);
        WindowId = new SDLWindowId((int)SDL.SDL_GetWindowID(_window));
    }

    /// <summary>
    /// The rendering engine that renders in the window managed by <see langword="this"/> <see cref="SDLWindowManager"/>.
    /// </summary>
    public IRenderingEngine RenderingEngine { get; }

    /// <summary>
    /// An abstract representation of the window ID. The ID of windows generated using <see cref="this"/>
    /// <see cref="IWindowManager"/> must match with the respective window event generated by <see cref="IEventSystem"/>
    /// specified in an <see cref="Application"/> to ensure that events are sent to the right window.
    /// </summary>
    public IWindowId WindowId { get; }

    /// <summary>
    /// Whether the window is visible.
    /// </summary>
    public bool Visible
    {
        get
        {
            _lifeCycle.ThrowIfNotOnUIThread();
            return _visible;
        }

        set
        {
            _lifeCycle.ThrowIfNotOnUIThread();
            _visible = value;

            if (value)
            {
                SDL.SDL_ShowWindow(_window);
            }
            else
            {
                SDL.SDL_HideWindow(_window);
            }
        }
    }

    /// <summary>
    /// Dispose the window and deallocates all the graphical resources.
    /// </summary>
    public void Shutdown()
    {
        _lifeCycle.ThrowIfNotOnUIThread();
        RenderingEngine.Shutdown();
        if (_window != IntPtr.Zero) SDL.SDL_DestroyWindow(_window);
    }
}
