using RetroDev.UISharp.Windows;

namespace RetroDev.UISharp.Core.Windowing.Events;

/// <summary>
/// A window event generated by a low level event handler, that contains the <see cref="IWindowId"/> window reference, which depends on the event handler implementation.
/// </summary>
/// <typeparam name="TArgs">The event arguments that will be used when propagating this event to a specific <see cref="Window"/>.</typeparam>
/// <param name="windowId"></param>
/// <param name="args"></param>
public class WindowEventArgs<TArgs>(IWindowId windowId, TArgs args) where TArgs : EventArgs
{
    /// <summary>
    /// The window identifier, generated by the <see cref="IEventSystem"/> implementation.
    /// </summary>
    public IWindowId WindowId { get; } = windowId;

    /// <summary>
    /// The event to propagate when sending this event to a specific target <see cref="Window"/>.
    /// </summary>
    public TArgs Args { get; } = args;
}
