name: UISharp Pipeline

on:
  push:
    branches: [ "main", "feature/9-automatic-versioning" ]  # Trigger on push to these branches
  pull_request:
    branches: [ "*" ]  # Automatically trigger for any PR
  workflow_dispatch:
    inputs:
      workflow_type:
        description: "Select workflow type"
        required: true
        default: "default"
        type: choice
        options:
          - release
          - default

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full history for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Get version from UISharp
      id: ui_version
      run: |
        VERSION=$(dotnet gitversion /output json | jq -r '.SemVer')
        echo "UISharp version: $VERSION"
        echo "ui_version=$VERSION" >> $GITHUB_ENV

    - name: Upload Version File
      uses: actions/upload-artifact@v4
      with:
        name: version
        path: version.txt
      run: echo "$UI_VERSION" > version.txt

  build:
    needs: get-version  # Ensure we get the version first
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full history for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained -o publish/${{ matrix.rid }}

    - name: Create and Push Git Tag for UISharp
      if: github.ref == 'refs/heads/main'  # Only create and push tag for 'main' branch
      run: |
        VERSION=${{ env.ui_version }}  # Use the version from the previous step
        git tag "v$VERSION"  # Create a tag based on the version
        git push origin "v$VERSION"  # Push the tag to the remote repository

    - name: Upload Artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event.inputs.workflow_type == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: UISharp-${{ matrix.rid }}
        path: publish/${{ matrix.rid }}/*
