name: .NET Multi-Platform Build

on:
  push:
    branches: [ "main", "mvp" ]
  pull_request:
    branches: [ "main", "mvp" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rid: [win-x64, linux-x64, osx-x64]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish UISharp Library
      run: dotnet publish UISharp/UISharp.csproj -c Release -r ${{ matrix.rid }} --self-contained false -o publish/UISharp/${{ matrix.rid }}

    - name: Publish UISharp.IDE Application
      run: dotnet publish UISharp.IDE/UISharp.IDE.csproj -c Release -r ${{ matrix.rid }} --self-contained true -o publish/UISharp.IDE/${{ matrix.rid }}

    - name: Upload Library Artifacts (UISharp)
      uses: actions/upload-artifact@v4
      with:
        name: UISharp-${{ matrix.rid }}
        path: publish/UISharp/${{ matrix.rid }}/*

    - name: Upload Application Artifacts (UISharp.IDE)
      uses: actions/upload-artifact@v4
      with:
        name: UISharp.IDE-${{ matrix.rid }}
        path: publish/UISharp.IDE/${{ matrix.rid }}/*
