name: UISharp Pipeline

on:
  push:
    branches: [ "main" , "feature/9-automatic-versioning" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      workflow_type:
        description: "Select workflow type"
        required: true
        default: "default"
        type: choice
        options:
          - release
          - default

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      ui_version: ${{ steps.get_version.outputs.ui_version }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full history for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Create and Push Git Tag for UISharp
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/9-automatic-versioning') || github.event.inputs.workflow_type == 'release'
      run: |
        cd .\src\RetroDev.UISharp\
        nbgv tag
        git push origin --tags

  build:
    needs: versioning  # Ensures versioning completes first
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full history for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained -o publish/${{ matrix.rid }}

    - name: Upload Artifact
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/9-automatic-versioning') || github.event.inputs.workflow_type == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: UISharp-${{ matrix.rid }}
        path: publish/${{ matrix.rid }}/*
