name: .NET Multi-Platform Build

on:
  push:
    branches: [ "main", "mvp" ]
  pull_request:
    branches: [ "main", "mvp" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained -o publish/${{ matrix.rid }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UISharp-IDEs-${{ matrix.rid }}
        path: publish/${{ matrix.rid }}/*
