name: UISharp Pipeline

on:
  push:
    branches: [ "main" , "feature/9-automatic-versioning"]  # Trigger on push to these branches
  pull_request:
    branches: [ "*" ]  # Automatically trigger for any PR
  workflow_dispatch:
    inputs:
      workflow_type:
        description: "Select workflow type"
        required: true
        default: "default"
        type: choice
        options:
          - release
          - default

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained -o publish/${{ matrix.rid }}

    - name: Get version from UISharp
      id: ui_version
      run: |
        dotnet tool install --global GitVersion.Tool
        VERSION=$(dotnet gitversion /output json | jq -r '.SemVer')  # Get version from the UISharp project
        echo "::set-output name=ui_version::$VERSION"

    - name: Create and Push Git Tag for UISharp
      if: github.ref == 'refs/heads/main'  # Only create and push tag for 'main' branch
      run: |
        VERSION=${{ steps.ui_version.outputs.ui_version }}  # Use the version from UISharp
        git tag "v$VERSION"  # Create a tag based on the version
        git push origin "v$VERSION"  # Push the tag to the remote repository

    - name: Upload Artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event.inputs.workflow_type == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: UISharp-${{ matrix.rid }}
        path: publish/${{ matrix.rid }}/*
